version: '3.9'

services:
  strapi:
    container_name: strapi
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    image: strapi-dev:latest
    restart: unless-stopped
    env_file: ./apps/api/.env
    volumes:
      - ./apps/api/config:/app/apps/api/config
      - ./apps/api/src:/app/src
      - ./apps/api/package.json:/app/apps/api/package.json
      - ./apps/api/yarn.lock:/app/apps/api/yarn.lock
      - ./apps/api/.env:/app/apps/api/.env
      - ./apps/api/public/uploads:/app/apps/api/public/uploads
    ports:
      - 1337:1337
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    restart: always
    ports:
      - 3000:3000
