version: '3.8'

services:
  traefik:
    image: traefik:v2.9.4
    container_name: traefik
    networks:
      - strapi
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /letsencrypt:/letsencrypt
    ports:
      - 80:80
      - 443:443
    command:
      - --api.dashboard=true
      - --log.level=warning
      - --accesslog.format=json
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --certificatesresolvers.le.acme.email=test@example.com
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.le.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.tls.certResolver=le
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
    labels:
      traefik.enable: true
      traefik.http.routers.unmatchedwww.rule: HostRegexp(`{name:^www\..*}`)
      traefik.http.routers.unmatchedwww.service: noop@internal
      traefik.http.routers.unmatchedwww.priority: 2
      traefik.http.routers.matchlast.rule: PathPrefix(`/`)
      traefik.http.routers.matchlast.priority: 1
      traefik.http.routers.matchlast.middlewares: removewww
      traefik.http.middlewares.removewww.redirectregex.regex: ^https://(?:www\.)?(.*)
      traefik.http.middlewares.removewww.redirectregex.replacement: https://www.$${1}
      traefik.http.routers.dashboard.rule: Host(`www.traefik.localhost`)
      "traefik.http.routers.dashboard.tls.domains[0].main": traefik.localhost
      "traefik.http.routers.dashboard.tls.domains[0].sans": www.traefik.localhost
      traefik.http.routers.dashboard.service: api@internal
      traefik.http.routers.dashboard.middlewares: auth
      # credentials are test/test
      traefik.http.middlewares.auth.basicauth.users: test:$$apr1$$H6uskkkW$$IgXLP6ewTrSuBkTrqE8wj/
  strapi:
    container_name: strapi-dev
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile.dev
    restart: unless-stopped
    networks:
      - strapi
    volumes:
      - ./yarn.lock:/app/yarn.lock
      - ./package.json:/app/package.json
      - ./apps/api/config:/app/apps/api/config
      - ./apps/api/src:/app/apps/api/src
      - ./apps/api/package.json:/app/apps/api/package.json
      - ./apps/api/.env:/app/apps/api/.env
      - ./apps/api/public/uploads:/app/apps/api/public/uploads
    env_file: ./apps/api/.env
    labels:
      traefik.enable: true
      traefik.http.routers.strapi.rule: Host(`www.api.localhost`)
      "traefik.http.routers.strapi.tls.domains[0].main": api.localhost
      "traefik.http.routers.strapi.tls.domains[0].sans": www.api.localhost
      traefik.http.services.strapi.loadbalancer.server.port: 1337
  strapiDB:
    image: mysql:8
    container_name: strapiDB
    restart: unless-stopped
    networks:
      - strapi
    volumes:
      - strapi-data:/var/lib/mysql
      #- ./data:/var/lib/postgresql/data/ # if you want to use a bind folder
    ports:
      - 3306:3306
    env_file: ./apps/api/.env
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  frontend:
    container_name: frontend-dev
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile.dev
    restart: always
    networks:
      - strapi
    labels:
      traefik.enable: true
      traefik.http.routers.frontend.rule: Host(`www.localhost`)
      "traefik.http.routers.frontend.tls.domains[0].main": www.localhost
      "traefik.http.routers.frontend.tls.domains[0].sans": localhost
      traefik.http.services.frontend.loadbalancer.server.port: 3000
    volumes:
      - ./yarn.lock:/app/yarn.lock
      - ./package.json:/app/package.json
      - ./apps/frontend/src:/app/apps/frontend/src
      - ./apps/frontend/package.json:/app/apps/frontend/package.json
      - ./apps/frontend/.env:/app/apps/frontend/.env
      - ./apps/frontend/public:/app/apps/frontend/public
# Add more containers below (nginx, postgres, etc.)
# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
volumes:
  letsencrypt:
  strapi-data:


networks:
  strapi:
    driver: bridge
