version: '3.9'

services:
  strapi:
    container_name: strapi
    image: {{ env.BACKEND_IMAGE_URL }}
    environment:
      DATABASE_CLIENT: {{ env.DATABASE_CLIENT }}
      DATABASE_HOST: strapiDB
      DATABASE_NAME: {{ env.DATABASE_NAME }}
      DATABASE_USERNAME: {{ env.DATABASE_USERNAME }}
      DATABASE_PORT: {{ env.DATABASE_PORT }}
      DATABASE_PASSWORD: {{ env.DATABASE_PASSWORD }}
      APP_KEYS: {{ env.APP_KEYS }}
      API_TOKEN_SALT: {{ env.API_TOKEN_SALT }}
      JWT_SECRET: {{ env.JWT_SECRET }}
      ADMIN_JWT_SECRET: {{ env.ADMIN_JWT_SECRET }}
      AWS_ACCESS_KEY_ID: {{ env.AWS_ACCESS_KEY_ID }}
      AWS_ACCESS_SECRET: {{ env.AWS_ACCESS_SECRET }}
      AWS_REGION: {{ env.AWS_REGION }}
      AWS_BUCKET: {{ env.AWS_BUCKET }}
      STRAPI_PLUGIN_I18N_INIT_LOCALE_CODE: {{ env.STRAPI_PLUGIN_I18N_INIT_LOCALE_CODE }}
      NODE_ENV: {{ env.NODE_ENV }}
    restart: unless-stopped
    # for domain connection
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend.rule=Host(`{{ env.BACKEND_HOST }}`)
      - traefik.http.routers.backend.tls=true
      - traefik.http.routers.backend.tls.certresolver=myresolver
      - traefik.http.routers.backend.entrypoints=websecure
      - traefik.http.services.backend.loadbalancer.server.port=1337
    networks:
      - strapi
    depends_on:
      - strapiDB
  strapiDB:
    image: mysql:8
    container_name: strapiDB
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_USER: {{ env.DATABASE_USERNAME }}
      MYSQL_ROOT_PASSWORD: {{ env.DATABASE_PASSWORD }}
      MYSQL_PASSWORD: {{ env.DATABASE_PASSWORD }}
      MYSQL_DATABASE: {{ env.DATABASE_NAME }}
    volumes:
      - strapi-data:/var/lib/mysql
      #- ./data:/var/lib/postgresql/data/ # if you want to use a bind folder
    ports:
      - 3306:3306
    networks:
      - strapi
  front:
    image: {{ env.FRONT_IMAGE_URL }}
    container_name: front
    environment:
      ENV_VARIABLE: {{ env.ENV_VARIABLE }}
      NEXT_PUBLIC_ENV_VARIABLE: {{ env.NEXT_PUBLIC_ENV_VARIABLE }}
      ANALYZE: {{ env.ANALYZE }}
      NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID: {{ env.NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID }}
    restart: always
    networks:
      - strapi
    # for domain connection
    labels:
      - traefik.enable=true
      - traefik.http.routers.front.rule=Host(`{{ env.FRONT_HOST }}`)
      - traefik.http.routers.front.tls=true
      - traefik.http.routers.front.tls.certresolver=myresolver
      - traefik.http.routers.front.entrypoints=websecure
      - traefik.http.services.front.loadbalancer.server.port=3000
  traefik:
    image: traefik:v2.9.4
    container_name: traefik
    command:
      - --log.level=DEBUG
      - --api=true
      - --api.insecure=true
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesResolvers.myresolver.acme.tlschallenge=true
      - --certificatesresolvers.myresolver.acme.caserver=https://acme-v02.api.letsencrypt.org/directory
      # - --certificatesresolvers.staging.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.myresolver.acme.email={{ env.CERTS_EMAIL }}
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
    restart: always
    networks:
      - strapi
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.enable=true
      # Dashboard
      - traefik.http.routers.traefik.rule=Host(`{{ env.TRAEFIK_HOST }}`)
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.certresolver=myresolver
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.service=api@internal
      # global redirect to https
      - traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)
      - traefik.http.routers.http-catchall.entrypoints=web
      - traefik.http.routers.http-catchall.middlewares=redirect-to-https
      # middleware redirect
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.traefik.middlewares=auth
      # Note: all dollar signs in the hash need to be doubled for escaping.
      # Passwords must be hashed using BCrypt.
      - traefik.http.middlewares.auth.basicauth.users={{ env.TRAEFIK_DASHBOARD_LOGIN }}:{{ env.TRAEFIK_DASHBOARD_PASSWORD }}

# Add more containers below (nginx, postgres, etc.)
# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
volumes:
  letsencrypt:
  strapi-data:

networks:
  strapi:
    name: Strapi
    driver: bridge
