FROM node:16-alpine AS builder
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk update && apk add build-base gcc autoconf automake zlib-dev libpng-dev nasm bash vips-dev libc6-compat
# Set working directory
WORKDIR /app
ENV NODE_ENV development
RUN yarn global add turbo
COPY . .
RUN turbo prune --scope=api --docker

FROM node:16-alpine AS runner
RUN apk update && apk add build-base gcc autoconf automake zlib-dev libpng-dev nasm bash vips-dev libc6-compat
# Set working directory
WORKDIR /app
ENV NODE_ENV development

COPY --from=builder /app/out/json/ .
COPY --from=builder /app/out/yarn.lock ./yarn.lock
RUN yarn config set network-timeout 600000 -g && yarn install

COPY --from=builder /app/out/full/ .
COPY turbo.json turbo.json
RUN yarn turbo run build

EXPOSE 1337

CMD yarn turbo run dev
